# Generated by Django 4.1.5 on 2023-01-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=255)),
                ("date", models.CharField(max_length=255)),
                ("value", models.CharField(max_length=255)),
                ("cpf", models.CharField(max_length=255)),
                ("card", models.CharField(max_length=255)),
                ("hour", models.CharField(max_length=255)),
                ("owner", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
    ]
